# Numpy & Pandas

In [1]:
import numpy as np

# np.array 로 n차원 매트릭스 만들기 가능
a1 = np.array([1, 2, 3]) 
print(a1)

[1 2 3]


In [2]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [3]:
a3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:
# arange로 0부터 n(전)까지의 수로 이뤄진 리스트를 만든다.
c = np.arange(15)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [5]:
c = c.reshape(3, 5)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [6]:
d = np.arange(0, 100, 5)
print(d)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [7]:
d = d.reshape(2, 2, 5)
print(d)

[[[ 0  5 10 15 20]
  [25 30 35 40 45]]

 [[50 55 60 65 70]
  [75 80 85 90 95]]]


In [8]:
n1 = np.array([[1, 0], [0,1]])
n2 = np.array([[1, 2], [3, 4]])

In [9]:
print(n1 + n2)

[[2 2]
 [3 5]]


In [10]:
print(n1 - n2)

[[ 0 -2]
 [-3 -3]]


In [11]:
print(n1 * n2)

[[1 0]
 [0 4]]


In [12]:
print(n2 / n1)

[[ 1. inf]
 [inf  4.]]


C:\Users\jylee\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [13]:
print(n1 + 1)

[[2 1]
 [1 2]]


In [14]:
print(n1-1)

[[ 0 -1]
 [-1  0]]


In [15]:
print(n1 * 2)

[[2 0]
 [0 2]]


In [16]:
n3 = np.arange(12).reshape(3, 4)
print(n3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
n3.sum(axis = 0) # 열의 합

array([12, 15, 18, 21])

In [18]:
n3.sum(axis = 1) # 행의 합

array([ 6, 22, 38])

In [19]:
n3.max(axis = 1) # 각 행에서의 최대값

array([ 3,  7, 11])

In [20]:
n3.max(axis = 0 ) # 각 열에서의 최대값

array([ 8,  9, 10, 11])

In [21]:
v = np.arange(20).reshape(4,5)
print(v)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [22]:
v[1, 2]  # 2번째 행의 3번째 열

7

In [23]:
v[1][2]

7

In [24]:
v[:,2]

array([ 2,  7, 12, 17])

In [25]:
v[:3, 0]

array([ 0,  5, 10])

In [26]:
v[1, :]

array([5, 6, 7, 8, 9])

1차원 데이터, 즉 한 열(줄)만 있는 데이터를 처리할 때는 시리즈를 사용한다.

(성능향상을 위해 데이터프레임 대신 series를 사용하는 것)

In [27]:
import pandas as pd

In [28]:
prices = [1000, 1010, 1020]
print(prices)

[1000, 1010, 1020]


In [29]:
dates = pd.date_range('20181201', periods = 3)
print(dates)

DatetimeIndex(['2018-12-01', '2018-12-02', '2018-12-03'], dtype='datetime64[ns]', freq='D')


In [30]:
s = pd.Series(prices, index = dates)
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, dtype: int64

In [31]:
a = pd.to_datetime('20181204')
s[a] = 1030

In [32]:
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
2018-12-04    1030
Freq: D, dtype: int64

In [33]:
s[1]

1010

In [34]:
s['2018-12-03']

1020

데이터프레임을 만드는 방법

    1. 딕셔너리를 만들어서 데이터프레임으로 변환
    2. 시리즈를 데이터프레임으로 변환

In [35]:
prices = { 'A전자' : [1000, 1010, 1020],
           'B화학' : [2000, 2010, 2020],
           'C금융' : [3000, 3010, 3020] }

df1 = pd.DataFrame(prices)
df1

A전자   B화학   C금융
0  1000  2000  3000
1  1010  2010  3010
2  1020  2020  3020

In [36]:
df2 = pd.DataFrame(prices, index = dates)
df2

A전자   B화학   C금융
2018-12-01  1000  2000  3000
2018-12-02  1010  2010  3010
2018-12-03  1020  2020  3020

## 데이터프레임 조회하기(인덱싱)

In [37]:
df2.iloc[1, 2]
# df2.iloc[줄번호, 열번호]

3010

In [38]:
df2.iloc[:, 0]
# 전체 행에서 첫번째 요소들

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [39]:
df2.loc['2018-12-01']
# loc은 인덱싱을 이름으로 한다.

A전자    1000
B화학    2000
C금융    3000
Name: 2018-12-01 00:00:00, dtype: int64

In [40]:
df2.loc[:,'A전자']

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [41]:
df2.loc['2018-12-02', 'C금융']

3010

In [42]:
#레이블 []로 열전체 가져오기
df2['A전자']

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: A전자, dtype: int64

In [43]:
df2['A전자']['2018-12-01']
# 열 먼저 주고 행 주기

1000

In [44]:
df2['D엔터'] = [4000, 4010, 4020] #리스트를 만들어서 추가한다.

df2

A전자   B화학   C금융   D엔터
2018-12-01  1000  2000  3000  4000
2018-12-02  1010  2010  3010  4010
2018-12-03  1020  2020  3020  4020

In [45]:
df2['E텔레콤'] = s
df2

A전자   B화학   C금융   D엔터  E텔레콤
2018-12-01  1000  2000  3000  4000  1000
2018-12-02  1010  2010  3010  4010  1010
2018-12-03  1020  2020  3020  4020  1020

In [46]:
s.name = 'F소프트'
s

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
2018-12-04    1030
Freq: D, Name: F소프트, dtype: int64

In [47]:
df2 = pd.concat([df2, s], axis = 1)
df2

A전자     B화학     C금융     D엔터    E텔레콤  F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030

In [48]:
a = df2.loc['2018-12-01']
a = a + 60

In [49]:
a.name = pd.to_datetime('2018-12-07')
a

A전자     1060.0
B화학     2060.0
C금융     3060.0
D엔터     4060.0
E텔레콤    1060.0
F소프트    1060.0
Name: 2018-12-07 00:00:00, dtype: float64

In [50]:
df2 = df2.append(a)

In [51]:
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [52]:
b = df2.iloc[0]
b = b + 50
b.name = pd.to_datetime('2018-12-06')
df2 = df2.append(b)

In [53]:
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0

In [54]:
df2 = df2.sort_index(axis = 0)

In [55]:
df2.drop([pd.to_datetime('2018-12-06'), pd.to_datetime('2018-12-02')])

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [56]:
df2.drop(['A전자', 'C금융'], axis = 1)

B화학     D엔터    E텔레콤    F소프트
2018-12-01  2000.0  4000.0  1000.0  1000.0
2018-12-02  2010.0  4010.0  1010.0  1010.0
2018-12-03  2020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN  1030.0
2018-12-06  2050.0  4050.0  1050.0  1050.0
2018-12-07  2060.0  4060.0  1060.0  1060.0

In [57]:
df2

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04     NaN     NaN     NaN     NaN     NaN  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [58]:
df2.dropna()

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0

In [59]:
df2.fillna(method = 'ffill')

A전자     B화학     C금융     D엔터    E텔레콤    F소프트
2018-12-01  1000.0  2000.0  3000.0  4000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  4010.0  1010.0  1010.0
2018-12-03  1020.0  2020.0  3020.0  4020.0  1020.0  1020.0
2018-12-04  1020.0  2020.0  3020.0  4020.0  1020.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  4050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  4060.0  1060.0  1060.0